<?php

namespace App\Services;

class DatabaseFieldConfig
{
    public static function config(): array
    {
        return [
            'data_konsumen' => [
                'labels' => [
                    'id_kavling' => 'ID Kavling',
                    'no_ktp' => 'NIK',
                    'nama_konsumen' => 'Nama Konsumen',
                    'tanggal_lahir' => 'Tanggal Lahir',
                    'pekerjaan' => 'Pekerjaan',
                    'detail_pekerjaan' => 'Detail Pekerjaan',
                    'alamat' => 'Alamat',
                    'kelurahan' => 'Kelurahan',
                    'kecamatan' => 'Kecamatan',
                    'kabupaten/kota' => 'Kabupaten/Kota',
                    'no_hp' => 'No. HP',
                    'nama_kondar' => 'Nama Kontak Darurat',
                    'no_hp_kondar' => 'No. HP Kontak Darurat',
                    'status_cash' => 'Status Cash',
                    'status_konsumen' => 'Status Konsumen',
                    'keterangan' => 'Keterangan',
                    'umur' => 'Umur',
                    'proses_terakhir' => 'Proses Terakhir',
                    'status_terakhir' => 'Status Terakhir',
                    'status_kelengkapan' => 'Status Kelengkapan',
                ],
                'table' => ['id_kavling', 'nama_konsumen', 'no_hp', 'pekerjaan', 'status_konsumen', 'proses_terakhir', 'status_terakhir'],
                'form' => ['id_kavling', 'no_ktp', 'nama_konsumen', 'tanggal_lahir', 'pekerjaan', 'detail_pekerjaan', 'alamat', 'kelurahan', 'kecamatan', 'kabupaten/kota', 'no_hp', 'nama_kondar', 'no_hp_kondar', 'status_cash', 'status_konsumen', 'keterangan'],
                'full_width' => ['alamat', 'keterangan'],
                'money' => [],
                'date' => ['tanggal_lahir', 'proses_terakhir'],
                'hidden_form' => ['umur', 'proses_terakhir', 'status_terakhir', 'id_kons', 'status_kelengkapan'],
            ],
            'bi_checking' => [
                'labels' => [
                    'id_kavling' => 'ID Kavling',
                    'nama_konsumen' => 'Nama Konsumen',
                    'no_ktp' => 'NIK',
                    'tanggal_slik' => 'Tanggal SLIK',
                    'hasil_slik' => 'Hasil SLIK',
                    'keterangan' => 'Keterangan',
                ],
                'table' => ['id_kavling', 'nama_konsumen', 'tanggal_slik', 'hasil_slik'],
                'form' => ['id_kavling', 'nama_konsumen', 'no_ktp', 'tanggal_slik', 'hasil_slik', 'keterangan'],
                'full_width' => ['keterangan'],
                'money' => [],
                'date' => ['tanggal_slik'],
                'hidden_form' => ['id_bi'],
            ],
            'PSJB' => [
                'labels' => [
                    'id_kavling' => 'ID Kavling',
                    'nama_konsumen' => 'Nama Konsumen',
                    'tanggal_psjb' => 'Tanggal PSJB',
                    'nama_koordinator' => 'Nama Koordinator',
                    'nama_sales' => 'Nama Sales',
                    'harga_unit' => 'Harga Unit',
                    'tanggal_utj' => 'Tanggal UTJ',
                    'utj' => 'UTJ',
                    'tanggal_dp_klt' => 'Tanggal DP KLT',
                    'dp_all_in' => 'DP All In',
                    'nominal_cicilan' => 'Nominal Cicilan',
                    'jumlah_cicilan' => 'Jumlah Cicilan',
                    'luas_klt' => 'Luas KLT',
                    'harga_klt/m' => 'Harga KLT/m',
                    'harga_klt_m' => 'Harga KLT/m',
                    'harga_klt_total' => 'Harga KLT Total',
                    'cara_pembayaran' => 'Cara Pembayaran',
                    'nama_promo' => 'Nama Promo',
                ],
                'table' => ['id_kavling', 'nama_konsumen', 'tanggal_psjb', 'nama_sales', 'harga_unit', 'utj', 'dp_all_in'],
                'form' => ['id_kavling', 'tanggal_psjb', 'nama_koordinator', 'nama_sales', 'harga_unit', 'tanggal_utj', 'utj', 'tanggal_dp_klt', 'dp_all_in', 'nominal_cicilan', 'jumlah_cicilan', 'luas_klt', 'harga_klt/m', 'harga_klt_m', 'harga_klt_total', 'cara_pembayaran', 'nama_promo'],
                'full_width' => [],
                'money' => ['harga_unit', 'utj', 'dp_all_in', 'nominal_cicilan', 'harga_klt_total'],
                'date' => ['tanggal_psjb', 'tanggal_utj', 'tanggal_dp_klt'],
                'hidden_form' => ['id_psjb'],
            ],
            'pemberkasan' => [
                'labels' => [
                    'id_kavling' => 'ID Kavling',
                    'nama_konsumen' => 'Nama Konsumen',
                    'tanggal_terima_bank' => 'Tanggal Terima Bank',
                    'bank' => 'Bank',
                    'kc/unit' => 'KC/Unit',
                    'kc_unit' => 'KC/Unit',
                    'request_plafond' => 'Request Plafond',
                    'request_tenor' => 'Request Tenor',
                    'tipe_pemberkasan' => 'Tipe Pemberkasan',
                ],
                'table' => ['id_kavling', 'nama_konsumen', 'tanggal_terima_bank', 'bank', 'request_plafond', 'request_tenor'],
                'form' => ['id_kavling', 'tanggal_terima_bank', 'bank', 'kc/unit', 'kc_unit', 'request_plafond', 'request_tenor', 'tipe_pemberkasan'],
                'full_width' => [],
                'money' => ['request_plafond'],
                'date' => ['tanggal_terima_bank'],
                'hidden_form' => ['id_berkas'],
            ],
            'proses_bank' => [
                'labels' => [
                    'id_kavling' => 'ID Kavling',
                    'nama_konsumen' => 'Nama Konsumen',
                    'no_sp3k' => 'No. SP3K',
                    'jenis_respon' => 'Jenis Respon',
                    'approved_plafond' => 'Approved Plafond',
                    'approved_tenor' => 'Approved Tenor',
                    'kategori_revisi' => 'Kategori Revisi',
                    'detail_revisi' => 'Detail Revisi',
                    'kendala' => 'Kendala',
                ],
                'table' => ['id_kavling', 'nama_konsumen', 'no_sp3k', 'jenis_respon', 'approved_plafond', 'approved_tenor'],
                'form' => ['id_kavling', 'no_sp3k', 'jenis_respon', 'approved_plafond', 'approved_tenor', 'kategori_revisi', 'detail_revisi', 'kendala'],
                'full_width' => ['detail_revisi', 'kendala'],
                'money' => ['approved_plafond'],
                'date' => [],
                'hidden_form' => [],
            ],
            'ppjb_dev' => [
                'labels' => [
                    'id_kavling' => 'ID Kavling',
                    'nama_konsumen' => 'Nama Konsumen',
                    'tanggal_sp3k' => 'Tanggal SP3K',
                    'tanggal_ttd_ppjb' => 'Tanggal TTD PPJB',
                ],
                'table' => ['id_kavling', 'nama_konsumen', 'tanggal_sp3k', 'tanggal_ttd_ppjb'],
                'form' => ['id_kavling', 'tanggal_sp3k', 'tanggal_ttd_ppjb'],
                'full_width' => [],
                'money' => [],
                'date' => ['tanggal_sp3k', 'tanggal_ttd_ppjb'],
                'hidden_form' => ['id_ppjb_dev'],
            ],
            'akad' => [
                'labels' => [
                    'id_kavling' => 'ID Kavling',
                    'nama_konsumen' => 'Nama Konsumen',
                    'tanggal_akad' => 'Tanggal Akad',
                    'kualitas_akad' => 'Kualitas Akad',
                    'status_bangunan' => 'Status Bangunan',
                    'status_dp_konsumen' => 'Status DP Konsumen',
                    'status_utilitas' => 'Status Utilitas',
                    'status_konsumen' => 'Status Konsumen',
                    'keterangan_terlambat' => 'Keterangan Terlambat',
                ],
                'table' => ['id_kavling', 'nama_konsumen', 'tanggal_akad', 'kualitas_akad', 'status_bangunan', 'status_dp_konsumen', 'status_utilitas'],
                'form' => ['id_kavling', 'tanggal_akad', 'kualitas_akad', 'status_bangunan', 'status_dp_konsumen', 'status_utilitas', 'status_konsumen', 'keterangan_terlambat'],
                'full_width' => ['keterangan_terlambat'],
                'money' => [],
                'date' => ['tanggal_akad'],
                'hidden_form' => ['no_ppjb_akad'],
            ],
            'bast' => [
                'labels' => [
                    'id_kavling' => 'ID Kavling',
                    'nama_konsumen' => 'Nama Konsumen',
                    'tanggal_bast' => 'Tanggal BAST',
                ],
                'table' => ['id_kavling', 'nama_konsumen', 'tanggal_bast'],
                'form' => ['id_kavling', 'tanggal_bast'],
                'full_width' => [],
                'money' => [],
                'date' => ['tanggal_bast'],
                'hidden_form' => ['no_bast'],
            ],
        ];
    }
}
