@php($value = fn (string $key, mixed $default = null) => old($key, isset($user) ? data_get($user, $key, $default) : $default))
<div class="grid gap-4 md:grid-cols-2">
    <div><label class="font-[Helvetica] font-bold text-xs uppercase block mb-1">Nama Lengkap</label><input name="name" value="{{ $value('name') }}" required class="w-full border-2 border-black px-3 py-2 text-sm rounded-none">@error('name')<p class="text-[#e91d2a] text-xs mt-1 font-bold">{{ $message }}</p>@enderror</div>
    <div><label class="font-[Helvetica] font-bold text-xs uppercase block mb-1">Email</label><input type="email" name="email" value="{{ $value('email') }}" required class="w-full border-2 border-black px-3 py-2 text-sm rounded-none">@error('email')<p class="text-[#e91d2a] text-xs mt-1 font-bold">{{ $message }}</p>@enderror</div>
    <div><label class="font-[Helvetica] font-bold text-xs uppercase block mb-1">Telepon</label><input name="phone" value="{{ $value('phone') }}" class="w-full border-2 border-black px-3 py-2 text-sm rounded-none">@error('phone')<p class="text-[#e91d2a] text-xs mt-1 font-bold">{{ $message }}</p>@enderror</div>
    <div><label class="font-[Helvetica] font-bold text-xs uppercase block mb-1">Peran</label><select name="role_id" required class="w-full border-2 border-black px-3 py-2 text-sm bg-white rounded-none"><option value="">Pilih peran</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected((int) $value('role_id') === (int) $role->id)>{{ $role->name }}</option>@endforeach</select>@error('role_id')<p class="text-[#e91d2a] text-xs mt-1 font-bold">{{ $message }}</p>@enderror</div>
    <div><label class="font-[Helvetica] font-bold text-xs uppercase block mb-1">Cabang Utama</label><select name="branch_id" required class="w-full border-2 border-black px-3 py-2 text-sm bg-white rounded-none"><option value="">Pilih cabang</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((int) $value('branch_id') === (int) $branch->id)>{{ $branch->name }} ({{ $branch->code }})</option>@endforeach</select>@error('branch_id')<p class="text-[#e91d2a] text-xs mt-1 font-bold">{{ $message }}</p>@enderror</div>
    <div><label class="font-[Helvetica] font-bold text-xs uppercase block mb-1">Atasan Langsung</label><select name="supervisor_user_id" class="w-full border-2 border-black px-3 py-2 text-sm bg-white rounded-none"><option value="">Tidak ada</option>@foreach($supervisors as $supervisor)@if(!isset($user) || !$supervisor->is($user))<option value="{{ $supervisor->id }}" @selected((int) $value('supervisor_user_id') === (int) $supervisor->id)>{{ $supervisor->name }} - {{ $supervisor->role?->name }}</option>@endif @endforeach</select>@error('supervisor_user_id')<p class="text-[#e91d2a] text-xs mt-1 font-bold">{{ $message }}</p>@enderror</div>
</div>
@include('crm.admin-users._memberships')
@include('crm.admin-users._project-assignments')
