@extends('layouts.crm')
@section('title', 'Detail Pengguna - Oasis CRM')
@section('content')
<x-crm.page-header color="#8c9ae0" title="Detail Pengguna" />
<div class="grid gap-4 lg:grid-cols-3">
<section class="border-2 border-black bg-white lg:col-span-2"><div class="bg-black text-white p-2 text-xs font-bold">AKUN DAN ORGANISASI</div><dl class="grid sm:grid-cols-2 gap-3 p-4 text-sm"><div><dt class="font-bold">Nama</dt><dd>{{ $user->name }}</dd></div><div><dt class="font-bold">Email</dt><dd>{{ $user->email }}</dd></div><div><dt class="font-bold">Telepon</dt><dd>{{ $user->phone ?: '-' }}</dd></div><div><dt class="font-bold">Peran</dt><dd>{{ $user->role?->name }}</dd></div><div><dt class="font-bold">Cabang Utama</dt><dd>{{ $user->branch?->name ?: '-' }}</dd></div><div><dt class="font-bold">Cabang Tambahan</dt><dd>{{ $user->branches->where('id','!=',$user->branch_id)->pluck('name')->join(', ') ?: '-' }}</dd></div><div><dt class="font-bold">Proyek</dt><dd>{{ $user->assignedProjects->pluck('project_name')->join(', ') ?: '-' }}</dd></div><div><dt class="font-bold">Atasan</dt><dd>{{ $user->supervisor?->name ?: '-' }}</dd></div><div><dt class="font-bold">Status</dt><dd>{{ str_replace('_',' ',strtoupper($user->account_status->value)) }}</dd></div><div><dt class="font-bold">Login Terakhir</dt><dd>{{ $user->last_login_at?->format('d/m/Y H:i') ?: '-' }}</dd></div></dl></section>
<aside class="border-2 border-black bg-white"><div class="bg-black text-white p-2 text-xs font-bold">TINDAKAN</div><div class="p-3 space-y-2 text-xs">
@can('update',$user)<a href="{{ route('admin-users.edit',$user) }}" class="block border-2 border-black p-2 font-bold text-center">EDIT</a>@endcan
@if(in_array($user->account_status,[\App\Enums\AccountStatus::PendingInvitation,\App\Enums\AccountStatus::Invited]))
@can('users.invite')<form method="POST" action="{{ route($user->account_status===\App\Enums\AccountStatus::PendingInvitation?'admin-users.invitation.send':'admin-users.invitation.resend',$user) }}" onsubmit="return confirm('Kirim undangan ke pengguna ini?')">@csrf<button class="w-full border-2 border-black bg-[#8c9ae0] p-2 font-bold">{{ $user->account_status===\App\Enums\AccountStatus::PendingInvitation?'SEND INVITATION':'RESEND INVITATION' }}</button></form>@endcan
@if($user->latestInvitation?->isUsable())@can('users.invite')<form method="POST" action="{{ route('admin-users.invitation.revoke',$user) }}" onsubmit="return confirm('Cabut undangan aktif?')">@csrf @method('PATCH')<button class="w-full border-2 border-black p-2 font-bold">REVOKE INVITATION</button></form>@endcan @endif
@endif
@can('users.reset_password')<form method="POST" action="{{ route('admin-users.reset-access',$user) }}" onsubmit="return confirm('Kirim pemulihan akses?')">@csrf<button class="w-full border-2 border-black p-2 font-bold">RESET ACCESS</button></form>@endcan
@php($statusActions = match($user->account_status) { \App\Enums\AccountStatus::Active => ['suspend'=>'SUSPEND','deactivate'=>'DEACTIVATE'], \App\Enums\AccountStatus::Suspended => ['reactivate'=>'REACTIVATE','deactivate'=>'DEACTIVATE'], \App\Enums\AccountStatus::Inactive => ['reactivate'=>'REACTIVATE'], default => ['deactivate'=>'DEACTIVATE'] })
@foreach($statusActions as $action=>$label)@can('users.'.$action)<form method="POST" action="{{ route('admin-users.'.$action,$user) }}" onsubmit="return confirm('Ubah status akun ini?')">@csrf @method('PATCH')<input name="reason" required minlength="3" placeholder="Alasan" class="w-full border-2 border-black p-2 mb-1"><button class="w-full border-2 border-black p-2 font-bold">{{ $label }}</button></form>@endcan @endforeach
</div></aside>
<section class="border-2 border-black bg-white"><div class="bg-black text-white p-2 text-xs font-bold">RIWAYAT UNDANGAN</div><div class="divide-y-2 divide-black">@forelse($user->invitations as $invitation)<div class="p-3 text-xs">{{ $invitation->created_at->format('d/m/Y H:i') }} · {{ $invitation->accepted_at?'Diterima':($invitation->revoked_at?'Dicabut':($invitation->expires_at->isPast()?'Kedaluwarsa':'Aktif')) }}<br>Oleh {{ $invitation->inviter?->name ?: '-' }}</div>@empty<div class="p-3 text-xs">Belum ada undangan.</div>@endforelse</div></section>
<section class="border-2 border-black bg-white lg:col-span-2"><div class="bg-black text-white p-2 text-xs font-bold">RIWAYAT AKTIVITAS</div><div class="divide-y-2 divide-black max-h-80 overflow-y-auto">@forelse($user->activityLogs as $log)<div class="p-3 text-xs"><strong>{{ $log->description }}</strong><br>{{ $log->created_at->format('d/m/Y H:i') }} · {{ $log->causer?->name ?: 'Sistem' }}</div>@empty<div class="p-3 text-xs">Belum ada aktivitas.</div>@endforelse</div></section>
</div>
@endsection
