@extends('layouts.crm')
@section('title', 'Migrasi Marison V2')
@section('content')
<x-crm.page-header variant="canonical" eyebrow="Administrasi" title="Migrasi Marison V2" description="Unggah paket JSON Marison V2.5.50, validasi kontrak, lalu tinjau sebelum impor.">
    <x-slot:actions><x-crm.button variant="secondary" :href="route('admin.marison-migrations.reconciliation.index')">Perlu Dicocokkan</x-crm.button><x-crm.button variant="secondary" :href="route('admin.marison-migrations.history')">Riwayat Batch</x-crm.button></x-slot:actions>
</x-crm.page-header>
<div class="grid gap-5 lg:grid-cols-2">
<x-crm.card><h2 class="mb-3 text-sm font-bold uppercase">Unggah Paket</h2><form method="POST" action="{{ route('admin.marison-migrations.preview') }}" enctype="multipart/form-data" class="space-y-3">@csrf<x-crm.field label="Paket JSON" for="marison-package" required :error="$errors->first('package')"><input id="marison-package" name="package" type="file" accept=".json,application/json" class="crm-control" required></x-crm.field><p class="text-xs text-gray-600">Maksimal 20 MB. Paket tidak boleh memuat nama konsumen, NIK, telepon, atau alamat.</p><x-crm.button type="submit" variant="primary">Validasi &amp; Preview</x-crm.button></form></x-crm.card>
<x-crm.card><h2 class="mb-3 text-sm font-bold uppercase">Pemetaan Proyek Eksplisit</h2><form method="POST" action="{{ route('admin.marison-migrations.mappings.store') }}" class="space-y-3">@csrf<x-crm.field label="Kode Cabang" for="mapping-branch" required><select id="mapping-branch" name="branch_code" class="crm-control" required>@foreach($branches as $branch)<option value="{{ $branch->code }}">{{ $branch->code }} — {{ $branch->name }}</option>@endforeach</select></x-crm.field><x-crm.field label="ID Proyek Sumber" for="mapping-source" required><input id="mapping-source" name="source_project_id" class="crm-control" required></x-crm.field><x-crm.field label="Proyek OASIS" for="mapping-project" required><select id="mapping-project" name="oasis_project_id" class="crm-control" required>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->branch?->code }} — {{ $project->project_name }}</option>@endforeach</select></x-crm.field><x-crm.button type="submit" variant="secondary">Simpan Pemetaan</x-crm.button></form></x-crm.card>
</div>
<x-crm.section title="Pemetaan Aktif" class="mt-5"><div class="crm-table-scroll"><table class="crm-data-table"><thead><tr><th>Cabang</th><th>ID Sumber</th><th>Proyek OASIS</th></tr></thead><tbody>@forelse($mappings as $mapping)<tr><td>{{ $mapping->branch_code }}</td><td>{{ $mapping->source_project_id }}</td><td>{{ $mapping->project?->project_name }}</td></tr>@empty<tr><td colspan="3">Belum ada pemetaan.</td></tr>@endforelse</tbody></table></div></x-crm.section>
@endsection
