@extends('layouts.crm')
@section('title', 'Preview Migrasi Marison')
@section('content')
<x-crm.page-header variant="canonical" eyebrow="Migrasi Marison V2" title="Preview Batch {{ $batch->public_id }}" description="Cabang {{ $batch->source_branch_code }} · Versi {{ $batch->source_version }} · Status {{ $batch->status }}"><x-slot:actions><x-crm.button variant="secondary" :href="route('admin.marison-migrations.create')">Kembali</x-crm.button></x-slot:actions></x-crm.page-header>
<div class="grid grid-cols-2 gap-3 lg:grid-cols-5">@foreach(['READY','ALREADY_IMPORTED','SOURCE_CHANGED_REVIEW','NEEDS_REVIEW','BLOCKED'] as $status)<x-crm.card><div class="text-xs font-bold uppercase">{{ $status }}</div><strong class="text-xl">{{ data_get($batch->counts, 'outcomes.'.$status, 0) }}</strong></x-crm.card>@endforeach</div>
<x-crm.section title="Transaksi" class="mt-5"><div class="crm-table-scroll"><table class="crm-data-table"><thead><tr><th>ID Transaksi</th><th>Proyek Sumber</th><th>Proyek OASIS</th><th>Hasil</th><th>Catatan</th></tr></thead><tbody>@foreach($batch->transactions as $row)<tr><td>{{ $row->source_transaction_id }}</td><td>{{ $row->source_project_id }}</td><td>{{ $row->projectMapping?->project?->project_name ?: '-' }}</td><td><x-crm.status-badge :variant="$row->outcome === 'READY' ? 'success' : ($row->outcome === 'BLOCKED' ? 'danger' : 'warning')">{{ $row->outcome }}</x-crm.status-badge></td><td>{{ collect($row->errors)->join('; ') ?: '-' }}</td></tr>@endforeach</tbody></table></div></x-crm.section>
<x-crm.section title="Unlinked Records ({{ $batch->unlinkedRecords->count() }})" class="mt-5"><div class="crm-table-scroll"><table class="crm-data-table"><thead><tr><th>Sheet</th><th>Baris</th><th>ID</th><th>Alasan</th></tr></thead><tbody>@forelse($batch->unlinkedRecords as $row)<tr><td>{{ $row->source_sheet }}</td><td>{{ $row->source_row ?? '-' }}</td><td>{{ $row->source_id ?? '-' }}</td><td>{{ $row->reason }}</td></tr>@empty<tr><td colspan="4">Tidak ada unlinked record.</td></tr>@endforelse</tbody></table></div></x-crm.section>
@if($batch->status === 'PREVIEW_READY' && data_get($batch->counts, 'outcomes.BLOCKED', 0) === 0)<form method="POST" action="{{ route('admin.marison-migrations.batches.confirm', $batch) }}" class="mt-5" onsubmit="return confirm('Konfirmasi impor paket ini? Transaksi READY akan ditulis secara atomik.')">@csrf<input type="hidden" name="preview_hash" value="{{ $batch->preview_hash }}"><input type="hidden" name="preview_version" value="{{ $batch->preview_version }}"><x-crm.button type="submit" variant="primary">Konfirmasi Impor</x-crm.button></form>@endif
@endsection
