@extends('layouts.crm')

@section('title', 'NUP / Waiting List - Oasis CRM')

@section('content')
    <x-crm.page-header variant="canonical" eyebrow="Penjualan" title="NUP / Waiting List" description="Daftar calon konsumen yang belum memiliki kavling dan belum menjadi transaksi aktif.">
        <x-slot:actions><a href="{{ route('consumer-nups.create') }}" class="crm-button crm-button--primary">+ Tambah NUP</a></x-slot:actions>
    </x-crm.page-header>
    <x-crm.toolbar label="Cari NUP" class="mb-4"><form method="GET" action="{{ route('consumer-nups.index') }}" class="flex w-full flex-wrap gap-2"><input name="search" value="{{ $search }}" placeholder="Nomor NUP, nama, atau HP" class="crm-control min-w-0 flex-1"><button class="crm-button crm-button--secondary">Cari</button></form></x-crm.toolbar>
    <div class="hidden crm-table-scroll md:block"><table class="crm-data-table min-w-[760px]"><thead><tr><th>NUP</th><th>Nama</th><th>Minat Proyek</th><th>Tanggal Masuk</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($nups as $nup)<tr><td>{{ $nup->nup_number }}</td><td><strong>{{ $nup->customer?->name }}</strong><div class="text-xs text-gray-600">{{ $nup->customer?->phone ?: '—' }}</div></td><td>{{ $nup->project?->project_name ?: 'Belum dipilih' }}</td><td>{{ $nup->registered_at?->format('d M Y') }}</td><td><x-crm.status-badge variant="{{ $nup->status === 'converted' ? 'success' : 'warning' }}">{{ $nup->status === 'converted' ? 'Sudah jadi konsumen' : 'Menunggu' }}</x-crm.status-badge></td><td>@if($nup->status === 'waiting')<form method="POST" action="{{ route('consumer-nups.convert', $nup) }}">@csrf<input type="hidden" name="project_id" value="{{ $nup->project_id }}"><button class="font-bold text-[#0000ee] underline">Lanjut jadi Konsumen</button></form>@else<a class="font-bold text-[#0000ee] underline" href="{{ route('consumer-database.workspace.show', $nup->converted_application_id) }}">Buka transaksi</a>@endif</td></tr>@empty<tr><td colspan="6"><x-crm.empty-state title="Belum ada NUP" description="Tambahkan calon konsumen yang masih berada dalam waiting list." /></td></tr>@endforelse</tbody></table></div>
    <div class="grid gap-3 md:hidden">@forelse($nups as $nup)<article class="border-2 border-black bg-white p-3"><div class="flex items-start justify-between gap-3"><div><strong>{{ $nup->customer?->name }}</strong><p class="text-xs text-gray-600">{{ $nup->nup_number }} · {{ $nup->customer?->phone ?: 'HP belum ada' }}</p></div><x-crm.status-badge variant="warning">{{ $nup->status === 'waiting' ? 'Menunggu' : 'Dikonversi' }}</x-crm.status-badge></div><p class="mt-2 text-sm">{{ $nup->project?->project_name ?: 'Minat proyek belum dipilih' }}</p>@if($nup->status === 'waiting')<form method="POST" action="{{ route('consumer-nups.convert', $nup) }}" class="mt-3">@csrf<input type="hidden" name="project_id" value="{{ $nup->project_id }}"><button class="crm-button crm-button--primary w-full">Lanjut jadi Konsumen</button></form>@endif</article>@empty<x-crm.empty-state title="Belum ada NUP" description="Tambahkan calon konsumen yang masih berada dalam waiting list." />@endforelse</div>
    @if($nups->hasPages())<div class="mt-4">{{ $nups->links() }}</div>@endif
@endsection
