@extends('layouts.crm')
@section('title', 'Preview Import Data Konsumen - Oasis CRM')
@section('content')
<x-crm.page-header variant="canonical" eyebrow="Konsumen Progress" title="Preview Import Data Konsumen" description="Tinjau hasil mapping sebelum data lokal dibuat." />
<div class="mb-4 grid grid-cols-2 gap-0 border-2 border-black bg-white text-center text-xs font-bold sm:grid-cols-6">
    @foreach(['Total' => $batch->total_rows, 'Siap' => $batch->ready_rows, 'Sudah Ada' => $batch->already_imported_rows, 'Peringatan' => $batch->warning_rows, 'Review' => $batch->review_rows, 'Tidak Valid' => $batch->invalid_rows] as $label => $value)<div class="border-r border-black p-3">{{ $label }}<br><span class="text-xl">{{ $value }}</span></div>@endforeach
</div>
<div class="mb-4 border-2 border-black bg-white p-4 text-sm"><strong>{{ $batch->branch->name }}</strong> / {{ $batch->project->project_name }}<br>Sumber: TSV manual. Preview tidak mengubah data lokal.</div>
<div class="overflow-x-auto border-2 border-black bg-white"><table class="min-w-full text-left text-xs"><thead class="bg-black text-white"><tr><th class="p-2">Baris</th><th class="p-2">Status</th><th class="p-2">Nama</th><th class="p-2">NIK</th><th class="p-2">Tanggal Lahir</th><th class="p-2">Pekerjaan</th><th class="p-2">Phone</th><th class="p-2">Kavling</th><th class="p-2">Kelengkapan</th><th class="p-2">Catatan</th></tr></thead><tbody>@foreach($batch->rows as $row) @php($nik = $row->sensitive_data['nik'] ?? null) <tr class="border-t border-gray-300"><td class="p-2">{{ $row->line_number }}</td><td class="p-2 font-bold">{{ $row->status }}</td><td class="p-2">{{ $row->normalized_data['name'] ?? '' }}</td><td class="p-2">{{ $nik ? '************'.substr($nik, -4) : '—' }}</td><td class="p-2">{{ $row->normalized_data['date_of_birth'] ?? '—' }}</td><td class="p-2">{{ $row->normalized_data['occupation'] ?? '—' }}</td><td class="p-2">{{ $row->normalized_data['phone'] ?? '' }}</td><td class="p-2">{{ $row->normalized_data['kavling'] ?? '' }}</td><td class="p-2">{{ data_get($row->normalized_data, 'completeness.complete') ? 'LENGKAP' : 'PERLU DILENGKAPI'.(data_get($row->normalized_data, 'completeness.missing') ? ': '.implode(', ', data_get($row->normalized_data, 'completeness.missing')) : '') }}</td><td class="p-2">{{ $row->skip_reason ? 'Dilewati: sebelumnya '.$row->skip_reason.'. ' : '' }}{{ implode(' ', array_merge($row->warnings ?? [], $row->errors ?? [])) }}</td></tr>@endforeach</tbody></table></div>
@if($batch->status === 'preview_ready')<form method="POST" action="{{ route('consumer-import.confirm', $batch) }}" class="mt-4 flex gap-2">@csrf<input type="hidden" name="expected_updated_at" value="{{ $batch->updated_at->toISOString() }}"><x-crm.button type="submit" variant="primary" accent="sales">Import Data Siap</x-crm.button><x-crm.button href="{{ route('consumer-import.create') }}" variant="secondary">Batal</x-crm.button></form>@else<div class="mt-4 border-2 border-black bg-[#d8f3dc] p-4 font-bold">Import selesai. Data lokal siap untuk reconciliation.</div>@endif
@endsection
