@extends('layouts.crm')
@section('title', 'Arsip Bukti Agenda Sales')
@section('content')
<x-crm.page-header variant="canonical" title="Arsip Bukti Agenda Sales" description="ZIP mingguan terverifikasi per cabang." />
<div class="grid gap-3 md:grid-cols-3"><x-crm.card><strong>{{ $archives->total() }}</strong><div>Total arsip</div></x-crm.card><x-crm.card><strong>{{ $archives->getCollection()->where('status', 'ready')->count() }}</strong><div>Terverifikasi pada halaman ini</div></x-crm.card><x-crm.card><strong>{{ $archives->getCollection()->sum(fn($archive) => count($archive->manifest['files'] ?? [])) }}</strong><div>File pada halaman ini</div></x-crm.card></div>
<x-crm.toolbar label="Filter arsip"><form method="GET" class="flex gap-2"><select name="branch_id" class="sales-input"><option value="">Semua cabang</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(request('branch_id') == $branch->id)>{{ $branch->name }}</option>@endforeach</select><x-crm.button type="submit" variant="secondary">Filter</x-crm.button></form></x-crm.toolbar>
<x-crm.section title="Bangun Arsip"><form method="POST" action="{{ route('sales-agendas.evidence-archives.build') }}" class="flex flex-wrap gap-2">@csrf<select name="branch_id" class="sales-input">@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select><input type="date" name="week" required class="sales-input"><x-crm.button type="submit" variant="primary" accent="sales">Bangun ZIP</x-crm.button></form></x-crm.section>
@if(auth()->user()->hasPrimaryRole('superadmin'))<x-crm.section title="Purge Manual"><p class="text-sm">File foto lokal yang dipilih akan dihapus dari storage aktif OASIS. Foto tetap tersimpan di Arsip ZIP yang telah diverifikasi. Tindakan ini tidak dapat dibatalkan dari OASIS.</p><form method="POST" action="{{ route('sales-agendas.evidence-archives.purge') }}" class="flex gap-2" onsubmit="return confirm('PURGE FILE LOKAL? File hanya dihapus setelah Arsip ZIP terverifikasi.')">@csrf<input type="number" name="days" min="60" value="60" required class="sales-input"><x-crm.button type="submit" variant="danger">PURGE FILE LOKAL</x-crm.button></form></x-crm.section>@endif
<div class="crm-table-scroll"><table class="crm-data-table"><thead><tr><th>Minggu</th><th>Cabang</th><th>Status</th><th>File</th><th>Aksi</th></tr></thead><tbody>@forelse($archives as $archive)<tr><td>{{ $archive->week_start->format('d/m/Y') }}</td><td>{{ $archive->branch?->name ?: '-' }}</td><td>{{ $archive->status }}</td><td>{{ count($archive->manifest['files'] ?? []) }}</td><td><a href="{{ route('sales-agendas.evidence-archives.download', $archive) }}">Download ZIP</a></td></tr>@empty<tr><td colspan="5">Belum ada arsip.</td></tr>@endforelse</tbody></table></div>{{ $archives->links() }}
@endsection
