@extends('layouts.crm')
@section('title', 'Bank - Oasis CRM')
@section('content')
<x-crm.page-header variant="canonical" title="Bank" eyebrow="Proses Konsumen" description="Pemberkasan dan Proses Bank untuk perjalanan konsumen yang sama." />
<div class="mb-4 border border-gray-300 bg-white p-4 text-sm"><strong>{{ $application->customer?->name }}</strong> · Kavling: {{ $application->kavling?->kavling_code ?? 'Belum Ada Data' }}</div>
<div class="mb-4 flex gap-2"><a href="{{ route('consumer-local.bank.create', $application) }}?stage=pemberkasan" class="border-2 border-black bg-[#fcc20f] px-3 py-2 font-bold">Pemberkasan</a><a href="{{ route('consumer-local.bank.create', $application) }}?stage=proses_bank" class="border border-gray-400 bg-white px-3 py-2 font-bold">Proses Bank</a></div>
@if(request('stage', 'pemberkasan') === 'proses_bank')
<form method="POST" action="{{ route('consumer-local.bank.store', $application) }}" class="grid gap-4 bg-white p-4 md:grid-cols-2">@csrf<input type="hidden" name="stage" value="proses_bank">@foreach(['no_sp3k'=>'No SP3K','response_type'=>'Jenis Respon','approved_plafond'=>'Approved Plafond','approved_tenor'=>'Approved Tenor','revision_category'=>'Kategori Revisi'] as $name => $label)<label class="text-xs font-bold uppercase">{{ $label }}<input name="{{ $name }}" value="{{ old($name) }}" class="mt-1 block w-full border border-gray-300 px-3 py-2" @required($name === 'no_sp3k' || $name === 'response_type')></label>@endforeach<label class="text-xs font-bold uppercase md:col-span-2">Detail Revisi<textarea name="revision_detail" class="mt-1 block w-full border border-gray-300 px-3 py-2"></textarea></label><label class="text-xs font-bold uppercase md:col-span-2">Kendala<textarea name="obstacle" class="mt-1 block w-full border border-gray-300 px-3 py-2"></textarea></label><button class="border-2 border-black bg-[#fcc20f] px-4 py-2 font-bold md:col-span-2">Simpan Proses Bank</button></form>
@else
<form method="POST" action="{{ route('consumer-local.bank.store', $application) }}" class="grid gap-4 bg-white p-4 md:grid-cols-2">@csrf<input type="hidden" name="stage" value="pemberkasan">@foreach(['tanggal_terima_bank'=>'Tanggal Terima Bank','bank_name'=>'Bank','kc_unit'=>'KC/Unit','request_plafond'=>'Request Plafond','request_tenor'=>'Request Tenor','tipe_pemberkasan'=>'Tipe Pemberkasan'] as $name => $label)<label class="text-xs font-bold uppercase">{{ $label }}<input name="{{ $name }}" type="{{ $name === 'tanggal_terima_bank' ? 'date' : 'text' }}" value="{{ old($name) }}" class="mt-1 block w-full border border-gray-300 px-3 py-2" @required($name === 'tanggal_terima_bank' || $name === 'bank_name')></label>@endforeach<label class="text-xs font-bold uppercase md:col-span-2">Keterangan<textarea name="notes" class="mt-1 block w-full border border-gray-300 px-3 py-2"></textarea></label><button class="border-2 border-black bg-[#fcc20f] px-4 py-2 font-bold md:col-span-2">Simpan Pemberkasan</button></form>
@endif
@endsection
